baseURL = "https://Dung-Le-1234.github.io/FCAJ-Full-Workshop/"
relativeURLs = false
canonifyURLs = true

theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  themeVariant = "workshop"
  editURL = ""
  description = ""
  author = "Dung Le"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

[Languages]

  [Languages.en]
  title = "Internship Report"
  weight = 1
  languageName = "English"

    [[Languages.en.menu.shortcuts]]
    name = "<i class='fab fa-facebook'></i> AWS Study Group"
    identifier = "AWS Study Group FB"
    url = "https://www.facebook.com/groups/awsstudygroupfcj/"
    weight = 20

  [Languages.vi]
  title = "Báo cáo thực tập"
  weight = 2
  languageName = "Tiếng Việt"

    [[Languages.vi.menu.shortcuts]]
    name = "<i class='fab fa-facebook'></i> AWS Study Group"
    identifier = "AWS Study Group FB"
    url = "https://www.facebook.com/groups/awsstudygroupfcj/"
    weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
